export const GET_EMBED_TO_INITIAL = "GET_EMBED_TO_INITIAL";
export const GET_EMBED_SUCCESS = "GET_EMBED_SUCCESS";
export const GET_EMBED_REJECTED = "GET_EMBED_REJECTED";

export const GET_TRACKS_SUCCESS = "GET_TRACKS_SUCCESS";
export const GET_TRACKS_REJECTED = "GET_TRACKS_REJECTED";

export const GET_QUERY_ASYNC = "GET_QUERY_ASYNC";
export const GET_QUERY_TO_INITIAL = "GET_QUERY_TO_INITIAL";

export const DOWLOAD_EMBED_ASYNC = "DOWLOAD_EMBED_ASYNC";

export const LOAD_MORE_ASYNC = "LOAD_MORE_ASYNC";
export const LOAD_MORE = "LOAD_MORE";